- tests/templates/inheritance/super
- tests/templates/inheritance/super_widget_base
- tests/templates/inheritance/super_widget_inherit
- tests/test_inherited.py
How's this? Is this the test you want.
I notice the other inheritance templates aren't actually used in any tests, but I wasn't sure exactly what they were supposed to test.
> Add tests for {{ block.super }} in widgets.

- sniplates/templatetags/sniplates.py
- tests/templates/inheritance/super
- tests/templates/inheritance/super_widget_base
- tests/templates/inheritance/super_widget_inherit
- tests/templates/reuse/simple
- tests/test_inherited.py
- tests/test_reuse.py
Rework handling of context.render_context so the right BlockContext is used when rendering widgets.
This means that {{ block.super }} in a widget block will work correctly.
> fix block context

- sniplates/templatetags/sniplates.py
- tests/templates/nested_tag/keep_widgets
- tests/templates/nested_tag/widgets
- tests/test_nested.py
The new template shows the issue quite well, I believe.
When using a nested_widget, you should be able to use widgets loaded in the template you are working in.
> Handle widgets used inside the content of a nested_widget.

- sniplates/templatetags/sniplates.py
- tests/test_filters.py
Since newer versions explicitly call mark_safe on the result, it's safe for us to do so as well.
https://github.com/django/django/blob/master/django/forms/utils.py#L26
> Make django1.4 flatatt a bit more like newer versions.

- docs/tags.rst
Because I genuinely ended up looking at the stacktrace first, assuming I'd broken the app somehow. I hadn't, I just hadn't paid enough attention to the docs, despite their, shall we say, brevity :)
> Made the alias info for form_field docs into an actual note

- MANIFEST.in
- setup.cfg
- setup.py
```
> pip install django-sniplates
Successfully installed django-sniplates Django
> cd lib/python2.7/site-packages/sniplates/
> tree .
.
├── __init__.py
├── models.py
└── templatetags
├── __init__.py
└── sniplates.py
1 directory, 4 files
```
So yeah, according to the `0.3.1` tag the `templates/sniplates/django.html` file should be part of the release, but it wasn't.
The following patch fixes that.
Used `check-manifest` (`pip install`) to generate the MANIFEST.in of what should definitely be in the sdist.
To check it works:
* run `setup.py build` and run `tree build` 
* run `pip install wheel`
* `setup.py bdist_wheel`
* rename the `.whl` file to `.zip` and unzip it, and then `tree` the directory extracted.
> Fixed packaging to include the templates

- docs/tags.rst
because case is preserved, and likely differs insofar as classes will be `CamelCase` and fields on the form will usually be `lower_case_with_underscores`
> Supplied an example of what names are searched for by {% form_field %}

- sniplates/templates/sniplates/django.html
- `CheckboxSelectMultiple` won't submit anything without a name. I'm expecting the same of `RadioSelect`. 
- `MultipleHiddenInput` looked to be the only widget using `name` rather than `html_name`
> HTML name attributes for default widget renderers

- sniplates/templates/sniplates/django.html
- sniplates/templatetags/sniplates.py
Given a `choices` of ([from the docs](https://docs.djangoproject.com/en/1.8/ref/models/fields/#choices)):
```
MEDIA_CHOICES = (
('Audio', (
('vinyl', 'Vinyl'),
('cd', 'CD'),
)
),
('Video', (
('vhs', 'VHS Tape'),
('dvd', 'DVD'),
)
),
('unknown', 'Unknown'),
)
```
the existing implementation doesn't do the same as Django's `Select` widget. This is me hacking out support for handling that use case.
WIP because:
- no tests
- no docs
- only done the single widget so far (need to cover the other widgets which use `choices`)
the new wrapper object should be backwards compatible with the old choices format I think, but thoughts and feedback would be appreciated.
> [WIP] Hacking out support for optgroup choices values.

- .travis.yml
- setup.py
- sniplates/templates/sniplates/django.html
- sniplates/templatetags/sniplates.py
- tests/forms.py
- tests/templates/field_tag/widgets_django
- tests/test_core.py
- tests/test_filters.py
- tests/test_forms.py
- tests/test_inherited.py
- tests/test_nested.py
- tests/test_reuse.py
- tests/test_widgets_django.py
- tests/utils.py
- tox.ini
I've noticed that there are some changes in ``sniplates/django.html`` needed (see also https://github.com/funkybob/django-sniplates/issues/36).
This initial PR adds tests for the default widgets with the correct expected output. The following commits will fix the failing test(s).
> Add test for the shipped widgets + fixes

- .coveragerc
- .travis.yml
- runtests.py
- setup.py
- tox.ini
* Make 'python setup.py test' working as expected
* Enabled coverage tracking in tests
* Let Travis use Tox instead of manually specifying the build matrix
Coverage results are pushed to Codecov and Coveralls. You would probably need to enable this repository there: https://codecov.io/, https://coveralls.io/. Codecov in general is a bit stricter than Coveralls (measuring branch coverage as well).
> Change Travis config to use tox and report coverage

- sniplates/templates/sniplates/django.html
I was a bit too eager - just noticed on a project that a test was failing because of this.
> Fix SelectOption value check

- sniplates/templates/sniplates/django.html
- sniplates/templatetags/sniplates.py
- tests/forms.py
- tests/templates/field_tag/widgets_django
- tests/test_widgets_django.py
This PR adds a test that checks (most) default widgets that are shipped with sniplates, with a bound form.
Contains **fixes**
* the (nullboolean)select that was merged yesterday
* fix for datetimebased widgets (DateField, DateTimeField, TimeField)
* fix for raw values passed in to NullBooleanField
I'll have to check if I still have missed something, but this should cover the majority of cases
> More tests for the default widgets

- runtests.py
- sniplates/templatetags/sniplates.py
- tests/forms.py
- tests/test_widgets_django.py
ChoiceWrapper was not behaving correctly with regard to detecting the value because the nested choices value was not `force_text`ed. I added the check in the test case for bound forms.
As a side effect, it turned out that building `ChoiceWrapper` as a simple `namedtuple` was not flexible enough, so I made it a proper object that quacks like a tuple.
Version bump + pypi release would be appropriate :-)
> Bugfix with ChoiceWrapper

- .travis.yml
- docs/index.rst
- runtests.py
- sniplates/templatetags/sniplates.py
- tests/test_core.py
- tests/test_filters.py
- tests/test_forms.py
- tests/test_inherited.py
- tests/test_nested.py
- tests/test_reuse.py
- tests/test_widgets_django.py
- tests/utils.py
- tox.ini
☑ Add Django 1.10 to the build config
☑ Drop < 1.8 support
☑ Fix 1.10 issues
☑ Update docs/readme
Since Django 1.7 is not officially supported by Django core anymore, it makes sense to drop support. This also allows us to use the new `TEMPLATES` settings which makes testing a bit more enjoyable.
Currently the shipped widgets library is failing on 1.10, I'm not sure what changed, but it seems to be related to the `{% for val, display in choices %}` where the unpacking seems to be ... funky.
> Add Django 1.10 support

- docs/changelog.rst
- setup.py
* Bumped version from 0.4.1 to 0.5.0 because of the Django 1.7 support drop
* Updated changelog
@funkybob if/when merged, can you also upload to PyPI?
> Prepare 0.5.0 release

- sniplates/templates/sniplates/django.html
Because the 'id' attribute was set for the label, the input element,
and the label use the same id. The new behavior is consistent with how
BoundField.label_tag works in Django.
Also see:
- https://docs.djangoproject.com/en/2.0/ref/forms/api/#django.forms.BoundField.id_for_label
- https://github.com/django/django/blob/master/django/forms/boundfield.py#L129
> In the example _label widget do not set an 'id' attribute for the label element.

- sniplates/templates/sniplates/django.html
- tests/test_widgets_django.py
For DateInput, DateTimeInput and TimeInput Django uses input_type 'text'. Align sniplates with this as well.
Using 'date', 'time' or 'datetime' is problematic because the HTML standard
defines specific formatting for these input types. For example type 'date'
requires a formatting of to be YYYY-MM-DD to be set in the 'value' attribute of
the input element.
However the DateInput, DateTimeInput and TimeInput widgets use
DATE_INPUT_FORMATS, DATETIME_INPUT_FORMATS and TIME_INPUT_FORMATS respectively
to format the value.  And these settings can, and often do, differ from what is
required by browser/HTML 5.
> Align with Django 'input_type' for date/time/datetime fields

- .travis.yml
- setup.py
- sniplates/templatetags/sniplates.py
- tests/test_widgets_django.py
* Added Python 3.8 to test matrix
* Updated PyPI classifiers
Django 3.0 currently crashes on the import of `django.utils.six`, and Python 2 is EOL.
> Drop Python 2 support, add Django 3 support

- pyproject.toml
- tests/test_widgets_django.py
Bump version
Increase the minimum Python version to allow Django 4.2 to install
Fix test for change made in Django 3.2.20 (works with earlier versions as well) - https://docs.djangoproject.com/en/4.2/releases/3.2.20/
> Support Django 4.2
